# Generated by Django 5.2 on 2025-04-05 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Ko‘rishlar')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stadiums', to=settings.AUTH_USER_MODEL, verbose_name='Menejer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadiums', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
        ),
        migrations.CreateModel(
            name='StadiumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stadiums/', verbose_name='Rasm')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stadiums.stadium', verbose_name='Stadion')),
            ],
        ),
        migrations.CreateModel(
            name='StadiumLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Manzil')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kenglik')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Uzunlik')),
                ('stadium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='stadiums.stadium', verbose_name='Stadion')),
            ],
        ),
    ]
