# Generated by Django 5.2 on 2025-04-07 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Bron', 'verbose_name_plural': 'Bronlar'},
        ),
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 soat'), (2, '2 soat'), (3, '3 soat')], default=1, verbose_name='Davomiyligi (soat)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Bron qilingan kun'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_hour',
            field=models.PositiveSmallIntegerField(choices=[(8, '08:00'), (9, '09:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00')], default=12, verbose_name='Boshlanish soati'),
        ),
    ]
