# Generated by Django 5.2 on 2025-04-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_booking_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_add',
            field=models.CharField(default=9125075975, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
