# Generated by Django 5.2 on 2025-04-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_phone_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_add',
            field=models.CharField(max_length=12),
        ),
    ]
