# Generated by Django 5.2 on 2025-04-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_rating_stadium_remove_rating_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start_hour',
            field=models.PositiveSmallIntegerField(choices=[(4, '04:00'), (5, '05:00'), (6, '06:00'), (7, '07:00'), (8, '08:00'), (9, '09:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00'), (24, '24:00')], default=12, verbose_name='Boshlanish soati'),
        ),
    ]
